# Trading Engine Configuration

# Environment settings
environment:
  timezone: "UTC"
  debug: false

# Data provider settings
alpaca:
  api_key: "YOUR_ALPACA_API_KEY" # Replace with your actual API key or use environment variables
  api_secret: "YOUR_ALPACA_API_SECRET" # Replace with your actual API secret
  base_url: "https://paper-api.alpaca.markets" # Paper trading URL
  data_url: "https://data.alpaca.markets"

# Interactive Brokers settings
interactive_brokers:
  host: "127.0.0.1"
  port: 7497 # TWS demo: 7497, IB Gateway demo: 4002
  client_id: 1

# Strategy parameters
strategies:
  momentum:
    lookback_period: 20
    threshold: 0.05
    rebalance_frequency: "daily"
  mean_reversion:
    lookback_period: 30
    z_score_threshold: 2.0
    rebalance_frequency: "daily"

# Risk management settings
risk:
  max_position_size: 0.10 # Maximum position size as percentage of portfolio
  max_portfolio_risk: 0.02 # Maximum portfolio risk (2% daily VaR)
  stop_loss_percentage: 0.05 # 5% stop loss
  take_profit_percentage: 0.10 # 10% take profit

# Backtesting settings
backtest:
  initial_capital: 100000
  start_date: "2022-01-01"
  end_date: "2022-12-31"
  include_commission: true
  commission_rate: 0.0005 # 5 basis points

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/trading_engine.log"
  max_size: 10485760 # 10 MB
  backup_count: 5

# Reporting configuration
reporting:
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
  output_directory: "reports"
  plots:
    - "equity_curve"
    - "drawdown"
    - "monthly_returns"
